version: "3.8"

services:
  client:
    build:
      context: "./"
      target: "develop-env"
    ports:
      - "8080:8080"
    volumes:
      - "./src:/app/src"
      - "./public:/app/public"
    command: "node_modules/.bin/vue-cli-service serve"
